    
version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=database
      - TOKEN_SECRET
    volumes:
      - ".:/usr/app"

  database:
    image: mongo